/**********************************************************************************************************************
  * This file is part of Scrupal, a Scalable Reactive Web Application Framework for Content Management                 *
  *                                                                                                                    *
  * Copyright (c) 2015, Reactific Software LLC. All Rights Reserved.                                                   *
  *                                                                                                                    *
  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance     *
  * with the License. You may obtain a copy of the License at                                                          *
  *                                                                                                                    *
  *     http://www.apache.org/licenses/LICENSE-2.0                                                                     *
  *                                                                                                                    *
  * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed   *
  * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for  *
  * the specific language governing permissions and limitations under the License.                                     *
  **********************************************************************************************************************/

import scrupal.sbt.project.ScrupalProjectPlugin
import scrupal.sbt.project.ScrupalProjectPlugin.autoImport._
import scoverage.ScoverageSbtPlugin

import sbt.Keys._
import sbt._

object ScrupalHMIBuild extends Build with Dependencies {

  val classesIgnoredByScoverage : String = Seq[String](
    "<empty>", // Avoids warnings from scoverage
    "scrupal.utils.ScrupalUtilsInfo", // Generated by sbt-buildinfo
    "scrupal.test.*", // Code used only for testing
    "scrupal.core.akkahttp.*", // Not currently in use, may be deleted in future
    "router.Routes.*", // Stuff generated by the Play Routes compiler
    "router.scrupal.core.javascript.*" // Javascript routes generated by Play Routes compiler

  ).mkString(";")

  val base_name = "scrupal"

  lazy val root = Project("scrupal-hmi", file("."))
    .enablePlugins(ScrupalProjectPlugin)
    .settings(
      organization := "org.scrupal",
      version := "0.1-SNAPSHOT",
      scalaVersion := Ver.scala,
      maxErrors := 50,
      resolvers ++= all_resolvers,
      //scalacOptions   += "-Xlog-implicits",
      scrupalTitle := "Scrupal Human-Machine Interface",
      scrupalPackage := "scrupal.hmi",
      ScoverageSbtPlugin.ScoverageKeys.coverageFailOnMinimum := true,
      ScoverageSbtPlugin.ScoverageKeys.coverageExcludedPackages := classesIgnoredByScoverage,
      ScoverageSbtPlugin.ScoverageKeys.coverageMinimum := 95,
      scrupalCopyrightHolder := "Reactific Software LLC",
      scrupalCopyrightYears := Seq(2013, 2014, 2015),
      scrupalDeveloperUrl := url("http://reactific.com/"),
      libraryDependencies ++= root_dependencies
    )
}
